### ISSUE TITLE
Demo has errors

### ISSUE THREAD

**Issue by blizam** [getgrav/grav-theme-boxify#3]
The buttons are out of whack, video player is broken, and the fontawesome icons are broken -- compared to here http://tympanus.net/Freebies/Boxify/

**Comment by flaviocopes** [comment]
Thanks for reporting, fixed by 

https://github.com/getgrav/grav-theme-boxify/commit/59282371bb986ccfc8480212315c852d3a737a88 
https://github.com/getgrav/grav-theme-boxify/commit/9a95a1dc3744f2138cc55393fd6aac1a00c3f51b
and
https://github.com/getgrav/grav-theme-boxify/commit/b96c6061c2c0e0ec2ac5947aedf61ec3addc1865

Going to make a release soon and rebuild the demo, you can grab the new theme files from github.
